name: Bug Report
description: Report a problem with the website
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem you encountered
      placeholder: "When I click on X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Page URL
      description: What page were you on when this happened?
      placeholder: "https://blog.example.com/blog/some-post"
    validations:
      required: false

  - type: dropdown
    id: device
    attributes:
      label: Device
      options:
        - Desktop
        - Mobile/Phone
        - Tablet
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: "Chrome, Safari, Firefox, etc."
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false
